const BIBLIOTECA = [
  {
    id: 'cpe2009',
    cat: 'constitucional',
    ley: 'CRBV 1999',
    nombre: 'Constitucion de la Republica Bolivariana de Venezuela',
    anio: '1999',
    organismo: 'Asamblea Nacional Constituyente',
    descripcion: 'Norma suprema de la Republica Bolivariana de Venezuela. Establece los derechos fundamentales, garantias constitucionales, estructura del Estado y los poderes publicos.',
    tags: ['amparo','libertad','derechos','garantias','TSJ','poder publico'],
    resumen: 'La CRBV de 1999 es la norma de mayor jerarquia en Venezuela. Consagra derechos civiles, politicos, economicos, sociales, culturales y colectivos, establece cinco poderes publicos (ejecutivo, legislativo, judicial, ciudadano y electoral) y reconoce los derechos de los pueblos indigenas.',
    articulos: [
      { num: 'Art. 13', texto: 'Los derechos reconocidos por esta Constitucion son inviolables, universales, interdependientes, indivisibles y progresivos.' },
      { num: 'Art. 109', texto: 'Todos los derechos reconocidos en la Constitucion son directamente aplicables y gozan de iguales garantias para su proteccion.' },
      { num: 'Art. 115', texto: 'Toda persona sera protegida oportuna y efectivamente por los jueces y tribunales en el ejercicio de sus derechos e intereses legitimos.' },
      { num: 'Art. 119', texto: 'Las partes en conflicto gozaran de igualdad de oportunidades para ejercer durante el proceso las facultades y los derechos que les asistan.' },
      { num: 'Art. 120', texto: 'Toda persona tiene derecho a ser oida por una autoridad jurisdiccional competente, independiente e imparcial, y no podra ser juzgada por comisiones especiales ni sometida a otras autoridades jurisdiccionales que las establecidas con anterioridad al hecho de la causa.' },
      { num: 'Art. 125', texto: 'Toda persona que considere que su vida esta en peligro, que es ilegalmente perseguida, o que es indebidamente procesada o privada de libertad personal, podra interponer Accion de Libertad.' },
      { num: 'Art. 27', texto: 'Toda persona tiene derecho a ser amparada por los tribunales en el goce y ejercicio de los derechos y garantias constitucionales, aun de aquellos inherentes a la persona que no figuren expresamente en esta Constitucion o en los instrumentos internacionales.' },
      { num: 'Art. 334', texto: 'El Tribunal Supremo de Justicia velara por la supremacia de la Constitucion, ejercera el control de constitucionalidad y precautelara el respeto y la vigencia de los derechos y las garantias constitucionales.' },
    ]
  },
  {
    id: 'lottt',
    cat: 'laboral',
    ley: 'LOTTT',
    nombre: 'Ley Organica del Trabajo, los Trabajadores y las Trabajadoras',
    anio: '2012',
    organismo: 'Presidencia de la Republica (Habilitante)',
    descripcion: 'Norma fundamental del derecho laboral venezolano. Regula contratos, jornada, salario, prestaciones sociales, sindicatos, inamovilidad y convenios colectivos.',
    tags: ['prestaciones sociales','inamovilidad','jornada','salario minimo','utilidades','bono vacacional','sindicato','contratacion colectiva'],
    resumen: 'La LOTTT es la norma base del derecho laboral venezolano. Establece la jornada de trabajo en 40h semanales diurnas y 35h nocturnas. Consagra las prestaciones sociales como derechos irrenunciables calculados mensualmente. Reconoce la inamovilidad laboral, el fuero maternal y la estabilidad relativa y absoluta. Regula utilidades (minimo 15 dias), bono vacacional y el contrato colectivo.',
    articulos: [
      { num: 'Art. 90 CRBV', texto: 'La jornada de trabajo diurna no excedera de ocho horas diarias ni de cuarenta y cuatro semanales. La jornada nocturna no excedera de siete horas.' },
      { num: 'Art. 141', texto: 'Todos los trabajadores y trabajadoras tienen derecho a prestaciones sociales que les recompensen la antiguedad en el servicio. Las prestaciones sociales constituyen deudas de valor y son de exigibilidad inmediata.' },
      { num: 'Art. 131', texto: 'El salario minimo es fijado por el Ejecutivo Nacional previo estudio y mediante Decreto. Ningun patrono podra pagar a sus trabajadores un salario inferior al minimo.' },
      { num: 'Art. 193', texto: 'La trabajadora embarazada o en periodo de lactancia goza de inamovilidad laboral. No podra ser trasladada, desmejora ni despedida sin justa causa calificada previamente por el Inspector del Trabajo.' },
      { num: 'Art. 132', texto: 'Los trabajadores tienen derecho a participar en los beneficios liquidos o utilidades de la empresa. La participacion minima sera el equivalente a quince dias de salario.' },
      { num: 'Art. 190', texto: 'Los trabajadores tendran derecho a un bono vacacional equivalente a siete dias de salario normal en el primer ano y uno adicional por cada ano hasta alcanzar veintiun dias.' },
    ]
  },
  {
    id: 'cp',
    cat: 'penal',
    ley: 'Ley 1768',
    nombre: 'Codigo Penal Venezolano',
    anio: '2005 (reforma)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Define los delitos y las penas aplicables en Venezuela. Cubre delitos contra la vida, propiedad, honor, familia, funcion publica y economia.',
    tags: ['homicidio','robo','estafa','violencia','corrupcion','delito','pena'],
    resumen: 'El CP venezolano clasifica los delitos en dolosos y culposos, con penas de prision, arresto y multa. Incluye circunstancias atenuantes, agravantes y eximentes. El COPP regula el proceso para juzgar estos delitos.',
    articulos: [
      { num: 'Art. 251', texto: 'El que matare a otro sera sancionado con presidio de cinco a veinte anos. Si el hecho fuere cometido con premeditacion, alevosía u otro agravante, la pena sera de quince a treinta anos.' },
      { num: 'Art. 271', texto: 'El que con violencia o intimidacion en las personas o fuerza en las cosas se apoderare de cosa mueble ajena sera sancionado con privacion de libertad de uno a cinco anos.' },
      { num: 'Art. 335', texto: 'El que con animo de lucro indujere en error a otro, mediante el empleo de artificios o enganos, y obtuviere para si o un tercero un beneficio ilicito, sera sancionado con privacion de libertad de uno a cinco anos.' },
      { num: 'Art. 13', texto: 'Solo podra ser condenado el que hubiere cometido la accion u omision punible con conciencia y voluntad. Nadie sera condenado sin que haya tenido la oportunidad de ser escuchado en juicio.' },
      { num: 'Art. 39', texto: 'Son circunstancias atenuantes generales: la buena conducta anterior, el arrepentimiento, obrar en estado de emocion violenta, ser menor de 21 anos, entre otras.' },
      { num: 'Art. 23', texto: 'Es autor quien realiza el hecho punible por si solo, conjuntamente con otro, o por medio de otro del que se sirve como instrumento.' },
    ]
  },
  {
    id: 'copp',
    cat: 'penal',
    ley: 'COPP',
    nombre: 'Codigo Organico Procesal Penal',
    anio: '2012 (reforma)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Regula el proceso penal venezolano: investigacion, acusacion, medidas cautelares, juicio oral y publico, y recursos. Sistema acusatorio con Ministerio Publico.',
    tags: ['privacion de libertad','imputacion','juicio oral','medidas cautelares','denuncia','Ministerio Publico','flagrancia'],
    resumen: 'El COPP establece el sistema acusatorio en Venezuela. El Ministerio Publico (Fiscalia) dirige la investigacion penal. La privacion judicial preventiva de libertad solo procede ante peligro de fuga u obstaculizacion. El juicio oral es publico y contradictorio ante escabinos (jueces legos). Reconoce el procedimiento abreviado para delitos flagrantes.',
    articulos: [
      { num: 'Art. 1', texto: 'Nadie podra ser condenado sin un juicio previo, oral y publico, realizado sin dilaciones indebidas, ante un juez o tribunal imparcial, conforme a las disposiciones de este Codigo.' },
      { num: 'Art. 127', texto: 'Todo imputado tiene derecho a ser asistido, desde los actos iniciales de la investigacion, por un defensor que designe el o sus parientes y, en su defecto, por un defensor publico.' },
      { num: 'Art. 236', texto: 'El juez de control podra decretar la privacion judicial preventiva de libertad cuando se acredite la existencia de un hecho punible, fundados elementos de conviccion de autoria y peligro de fuga u obstaculizacion.' },
      { num: 'Art. 244', texto: 'La privacion preventiva de libertad no podra exceder de dos anos, ni de la pena minima prevista para el delito. Al cumplirse este lapso, el juez decretara la libertad del imputado sin perjuicio de las medidas cautelares sustitutivas.' },
      { num: 'Art. 373', texto: 'El procedimiento abreviado aplica cuando el imputado sea sorprendido en flagrancia. El Ministerio Publico presentara directamente la acusacion ante el juez de juicio.' },
    ]
  },
  {
    id: 'cc',
    cat: 'civil',
    ley: 'Codigo Civil',
    nombre: 'Codigo Civil de Venezuela',
    anio: '1982 (reforma)',
    organismo: 'Congreso de la Republica',
    descripcion: 'Regula las relaciones juridicas entre personas: contratos, obligaciones, derechos reales, propiedad, herencia y responsabilidad civil.',
    tags: ['contrato','propiedad','herencia','prescripcion','obligacion','hipoteca'],
    resumen: 'El CC venezolano organiza el derecho privado. Regula la persona (natural y juridica), la familia, los contratos (compraventa, arrendamiento, mutuo, donacion), los bienes inmuebles y muebles, la herencia ab intestato y testamentaria, y la responsabilidad civil extracontractual.',
    articulos: [
      { num: 'Art. 450', texto: 'Hay contrato cuando dos o mas personas se ponen de acuerdo para constituir, modificar o extinguir entre si una relacion juridica.' },
      { num: 'Art. 584', texto: 'Por el contrato de compraventa el vendedor transfiere la propiedad de una cosa o un derecho al comprador, y este paga el precio.' },
      { num: 'Art. 1492', texto: 'Los derechos se extinguen por la prescripcion cuando su titular no los ejercita durante el tiempo que la ley establece.' },
      { num: 'Art. 999', texto: 'La propiedad es el poder juridico que permite usar, gozar y disponer de una cosa, y debe ejercerse en forma compatible con el interes colectivo.' },
      { num: 'Art. 1000', texto: 'La propiedad se adquiere por ocupacion, accesion, usucapion, sucesion hereditaria, contrato y demas modos establecidos por ley.' },
      { num: 'Art. 1098', texto: 'La usucapion es el modo de adquirir la propiedad y otros derechos reales mediante la posesion continuada, pacifica y publica durante el tiempo que establece la ley.' },
    ]
  },
  {
    id: 'lopnna',
    cat: 'familiar',
    ley: 'LOPNNA',
    nombre: 'Ley Organica para la Proteccion de Ninos, Ninas y Adolescentes',
    anio: '1998 (reforma 2015)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Protege integralmente a ninos, ninas y adolescentes en Venezuela. Regula la patria potestad, custodia, obligacion de manutension, adopcion y el sistema de proteccion.',
    tags: ['custodia','manutension','patria potestad','adopcion','IDENNA','convivencia familiar','filiacion'],
    resumen: 'La LOPNNA es la norma principal del derecho familiar venezolano relativo a menores. Establece el interes superior del nino como principio rector. Regula la patria potestad (ejercicio conjunto por ambos progenitores), la custodia, el regimen de convivencia familiar (visitas), la obligacion de manutension proporcional al ingreso del obligado, y el proceso de adopcion. Crea el IDENNA y los Consejos de Proteccion como organos administrativos.',
    articulos: [
      { num: 'Art. 8', texto: 'El interes superior del nino es un principio de interpretacion y aplicacion de esta Ley, el cual es de obligatorio cumplimiento en la toma de todas las decisiones concernientes a los ninos y adolescentes.' },
      { num: 'Art. 358', texto: 'La patria potestad comprende la guarda, la representacion y la administracion de los bienes de los hijos. En caso de desacuerdo, el juez determinara quien la ejerce.' },
      { num: 'Art. 365', texto: 'La custodia comprende el cuidado, crianza, formacion, educacion, guarda, vigilancia y orientacion moral y civil del nino. Puede ser otorgada a uno o ambos progenitores segun el interes superior del nino.' },
      { num: 'Art. 369', texto: 'La obligacion de manutension comprende la cobertura de las necesidades de los hijos: alimento, vestido, habitacion, educacion, salud, transporte, recreacion y deportes.' },
      { num: 'Art. 375', texto: 'La obligacion de manutension es proporcional a los recursos economicos del obligado. El tribunal fijara el monto tomando en cuenta los ingresos y el nivel de vida.' },
    ]
  },
  {
    id: 'ldmvlv',
    cat: 'familiar',
    ley: 'Ley sobre la Violencia contra la Mujer',
    nombre: 'Ley Organica sobre el Derecho de las Mujeres a una Vida Libre de Violencia',
    anio: '2007 (reforma 2021)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Tipifica y sanciona la violencia contra la mujer en Venezuela. Crea los tribunales especializados de violencia de genero y establece medidas de proteccion inmediata.',
    tags: ['violencia de genero','femicidio','medidas de proteccion','acoso','violencia psicologica','violencia sexual','tribunal de violencia'],
    resumen: 'Esta ley venezolana tipifica 21 formas de violencia contra la mujer (fisica, psicologica, sexual, patrimonial, acoso, femicidio, etc.). El femicidio tiene pena de 28 a 30 anos de prision. Crea tribunales penales especializados en violencia de genero. Las medidas de proteccion (alejamiento del agresor, orden de no acercamiento) son dictadas de forma inmediata por el Ministerio Publico o el tribunal.',
    articulos: [
      { num: 'Art. 14', texto: 'Se consideran formas de violencia contra la mujer: violencia psicologica, acoso u hostigamiento, amenaza, violencia fisica, violencia domestica, violencia sexual, acceso carnal violento, prostitucion forzada, esclavitud sexual, acoso sexual, violencia laboral, violencia patrimonial y economica, violencia obstetrica, esterilizacion forzada, violencia mediatica, violencia institucional, trafico de mujeres, femicidio y otros.' },
      { num: 'Art. 58', texto: 'El femicidio es la muerte violenta de una mujer por razones asociadas a su condicion de genero. Sera sancionado con pena de veintiocho a treinta anos de prision.' },
      { num: 'Art. 90', texto: 'Las medidas de proteccion y seguridad son de naturaleza preventiva. Podran ser dictadas de oficio o a solicitud de parte por el Ministerio Publico o el tribunal competente.' },
      { num: 'Art. 93', texto: 'Entre las medidas de proteccion se encuentran: orden de salida del agresor del hogar, prohibicion de acercamiento a la victima, prohibicion de portar armas y arresto transitorio del agresor.' },
    ]
  },
  {
    id: 'cocom',
    cat: 'mercantil',
    ley: 'Codigo de Comercio',
    nombre: 'Codigo de Comercio de Venezuela',
    anio: '1955 (vigente)',
    organismo: 'Congreso de los Estados Unidos de Venezuela',
    descripcion: 'Regula los actos de comercio, empresas, sociedades mercantiles (C.A., S.R.L.), contratos mercantiles, titulos valores y quiebra.',
    tags: ['SRL','CA','Registro Mercantil','titulos valores','quiebra','comerciante','sociedad'],
    resumen: 'El Codigo de Comercio venezolano regula la actividad empresarial en Venezuela. Define los tipos de sociedades: C.A. (acciones transables) y S.R.L. (responsabilidad limitada al capital). Todas las empresas deben registrarse en el Registro Mercantil. Incluye el regimen de titulos valores (cheque, letra de cambio, pagare).',
    articulos: [
      { num: 'Art. 195', texto: 'La sociedad de responsabilidad limitada es aquella que se constituye entre socios que son responsables hasta el monto de sus aportes al capital.' },
      { num: 'Art. 217', texto: 'La sociedad anonima es aquella en que el capital esta dividido en acciones y la responsabilidad de los socios se limita al valor de sus acciones.' },
      { num: 'Art. 492', texto: 'El cheque es un titulo valor por el que el girador ordena al banco girado el pago de una suma determinada en favor del beneficiario.' },
      { num: 'Art. 535', texto: 'La letra de cambio es un titulo valor que incorpora la obligacion de pagar una suma de dinero en el lugar y fecha indicados.' },
    ]
  },
  {
    id: 'lopa',
    cat: 'administrativo',
    ley: 'LOPA',
    nombre: 'Ley Organica de Procedimientos Administrativos',
    anio: '1981',
    organismo: 'Congreso de la Republica',
    descripcion: 'Establece los principios, plazos y recursos del procedimiento administrativo en toda la administracion publica venezolana.',
    tags: ['recurso','reconsideracion','jerarquico','acto administrativo','silencio administrativo','plazo','nulidad'],
    resumen: 'La LOPA regula como actua la administracion publica venezolana. Consagra principios de legalidad, economía procesal, celeridad y eficacia. Define los actos administrativos y sus requisitos de validez, los recursos administrativos (reconsideracion ante la misma autoridad, jerarquico ante el superior), el silencio administrativo negativo (60 dias) y la nulidad absoluta y relativa de los actos.',
    articulos: [
      { num: 'Art. 1', texto: 'La administracion publica nacional y la descentralizada estadal y municipal ajustaran su actividad a los prescripciones de la presente Ley.' },
      { num: 'Art. 9', texto: 'Los actos administrativos de caracter particular deberan ser motivados, excepto los de simple tramite. La motivacion debera ser suficiente.' },
      { num: 'Art. 94', texto: 'El recurso de reconsideracion debera intentarse dentro de los quince (15) dias siguientes a la notificacion del acto que se impugna, por ante el funcionario que lo dicto.' },
      { num: 'Art. 95', texto: 'El recurso jerarquico procedera contra todo acto administrativo de caracter particular. Debera interponerse dentro de los quince (15) dias siguientes a la notificacion del acto que se impugna.' },
      { num: 'Art. 4', texto: 'En los casos en que un organo de la administracion publica no resolviere un asunto en el lapso de noventa dias, el interesado podra considerar que la decision es contraria a su pretension (silencio administrativo negativo).' },
    ]
  },
  {
    id: 'lefp',
    cat: 'administrativo',
    ley: 'Ley del Estatuto de la Funcion Publica',
    nombre: 'Ley del Estatuto de la Funcion Publica',
    anio: '2002',
    organismo: 'Asamblea Nacional',
    descripcion: 'Regula los derechos, deberes y responsabilidades de los funcionarios publicos venezolanos y las relaciones de empleo publico.',
    tags: ['funcionario publico','carrera administrativa','destitución','suspension','concurso','Contraloria'],
    resumen: 'La LEFP regula la funcion publica en Venezuela. Establece la carrera administrativa por concurso publico, los derechos (estabilidad, jubilacion, permisos) y deberes de los funcionarios, las sanciones disciplinarias (amonestacion, suspension, destitución) y el recurso contencioso-administrativo funcionarial ante los tribunales laborales.',
    articulos: [
      { num: 'Art. 30', texto: 'Los funcionarios publicos de carrera que ocupen cargos de carrera gozaran de estabilidad en el desempeno de sus cargos. En consecuencia, solo podran ser retirados del servicio por las causales contempladas en la presente Ley.' },
      { num: 'Art. 78', texto: 'El retiro de la Administracion Publica procede por reduccion de personal, jubilacion, invalidez, destitución y otras causas previstas en la ley.' },
      { num: 'Art. 86', texto: 'Seran causales de destitución: el abandono injustificado al trabajo por mas de tres dias habiles, actos lesivos al buen nombre del organo, violacion de la confidencialidad de la informacion.' },
      { num: 'Art. 92', texto: 'Los funcionarios publicos podran ejercer recurso contencioso-administrativo funcionarial ante el Tribunal de la Carrera Administrativa en un lapso de tres meses.' },
    ]
  },
  {
    id: 'cot',
    cat: 'tributario',
    ley: 'Codigo Organico Tributario',
    nombre: 'Codigo Organico Tributario de Venezuela',
    anio: '2020 (reforma)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Regula los tributos nacionales en Venezuela. Establece derechos y deberes de los contribuyentes, el SENIAT, reparos fiscales y recursos tributarios.',
    tags: ['SENIAT','ISLR','IVA','tributo','reparo','contribuyente','recurso tributario'],
    resumen: 'El COT venezolano es la norma marco del sistema tributario. Regula la relacion juridico-tributaria entre el Estado (SENIAT) y los contribuyentes. Establece los deberes formales, el proceso de fiscalizacion, los reparos fiscales y los recursos administrativos y judiciales en materia tributaria.',
    articulos: [
      { num: 'Art. 1', texto: 'Las disposiciones de este Codigo Organico son aplicables a los tributos nacionales y a las relaciones juridicas derivadas de esos tributos.' },
      { num: 'Art. 145', texto: 'Los contribuyentes y responsables estan obligados a llevar en forma debida y oportuna los libros y registros especiales, conforme a las normas legales y los principios de contabilidad generalmente aceptados.' },
      { num: 'Art. 188', texto: 'La Administracion Tributaria podra practicar fiscalizaciones a los contribuyentes o responsables, las cuales se autorizaran a traves de providencia administrativa.' },
    ]
  },
  {
    id: 'lss',
    cat: 'laboral',
    ley: 'Ley del Seguro Social',
    nombre: 'Ley del Seguro Social (IVSS)',
    anio: '1967 (vigente con reformas)',
    organismo: 'Congreso de la Republica',
    descripcion: 'Regula el sistema de seguridad social venezolano: enfermedad, maternidad, vejez, invalidez, sobrevivencia y paro forzoso, administrado por el IVSS.',
    tags: ['jubilacion','pension','IVSS','seguridad social','paro forzoso','vejez','invalidez','cotizacion'],
    resumen: 'La Ley del Seguro Social venezolano crea el IVSS (Instituto Venezolano de los Seguros Sociales) como ente administrador. Las cotizaciones son obligatorias para empleadores y trabajadores. Cubre enfermedades, maternidad, accidentes laborales, vejez, invalidez y muerte. El paro forzoso da derecho a prestacion economica temporal por desempleo involuntario.',
    articulos: [
      { num: 'Art. 1', texto: 'El Seguro Social obligatorio se aplicara a los trabajadores que presten servicios a empleadores bajo dependencia, en virtud de un contrato de trabajo o en condiciones de hecho.' },
      { num: 'Art. 9', texto: 'La pension de invalidez se otorgara al asegurado que quede incapacitado para el trabajo en forma permanente, total o parcial, a consecuencia de enfermedad o accidente no profesional.' },
      { num: 'Art. 23', texto: 'Los beneficiarios de pension de vejez son los asegurados que hayan cumplido 60 anos los hombres y 55 las mujeres, con al menos 750 semanas de cotizacion.' },
      { num: 'Art. 30', texto: 'La cotizacion del seguro social se calcula sobre el salario normal del trabajador. El empleador retiene la parte del trabajador y paga su contribucion patronal en los plazos reglamentarios.' },
    ]
  },
  {
    id: 'islr',
    cat: 'tributario',
    ley: 'Ley de ISLR',
    nombre: 'Ley de Impuesto sobre la Renta (ISLR)',
    anio: '2015 (ultima reforma)',
    organismo: 'Asamblea Nacional',
    descripcion: 'Regula el impuesto que grava los enriquecimientos anuales, netos y disponibles obtenidos por personas naturales y juridicas en Venezuela.',
    tags: ['ISLR','renta','declaracion','SENIAT','enriquecimiento','UT','retenciones','persona juridica'],
    resumen: 'El ISLR venezolano grava los enriquecimientos netos anuales. Las personas naturales tributan con tarifas progresivas del 6% al 34%; las juridicas pagan tarifa del 15%, 22% o 34% segun el enriquecimiento neto. El SENIAT administra el impuesto. La declaracion definitiva se presenta en marzo del ano siguiente. Los anticipos (pagos a cuenta) son trimestrales para personas juridicas.',
    articulos: [
      { num: 'Art. 1', texto: 'Los enriquecimientos anuales, netos y disponibles obtenidos en dinero o en especie, causaran impuesto segun las normas establecidas en esta Ley.' },
      { num: 'Art. 7', texto: 'Estan sometidos al impuesto establecido en esta Ley: las personas naturales, las companias anonimas y las sociedades de responsabilidad limitada, entre otros.' },
      { num: 'Art. 50', texto: 'Los contribuyentes que obtengan enriquecimientos netos superiores a mil unidades tributarias (1.000 U.T.) anuales deberan presentar declaracion definitiva de rentas.' },
      { num: 'Art. 83', texto: 'El impuesto determinado segun la tarifa progresiva se reducira con los desgravamenes autorizados por la ley, entre ellos: pagos por servicios medicos, intereses de credito hipotecario para vivienda y los aportes al seguro social.' },
    ]
  }
];